<a href="https://colab.research.google.com/github/FIROZ-N/DSA-2025/blob/main/Numpy_%26_Pandas_Assignment_Firoz_Muhammed_N.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 NumPy array with values from 10 to 49 (inclusive).

 ----

● Reshape it into a 4x10 matrix.

----

● Then extract the last column from the reshaped matrix

In [ ]:
import numpy as np

arr = np.arange(10,50)

matrix = arr.reshape(4,10)

print()

print(f"matrix : {matrix}")

last_column = matrix[:,-1]

print(f"last : {last_column}")



matrix : [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
last : [19 29 39 49]


Two 3×3 matrices:

---
One filled with all 5s , One with values from 1 to 9

---
● Add the two matrices

---
● Multiply them element-wise

---
● Then find the transpose of the result

In [ ]:
import numpy as np

mat1 = np.full((3, 3), 5)
mat2 = np.arange(1, 10).reshape(3, 3)
added = mat1 + mat2
multiplied = mat1 * mat2
transpose_result = multiplied.T
print("\nTranspose of Element-wise Multiplication:\n", transpose_result)


Transpose of Element-wise Multiplication:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


A NumPy array of 15 random integers between 10 and 100.

----
● Replace all values greater than 50 with -1

----
● Count how many values were replaced.

In [ ]:
rand_arr = np.random.randint(10, 101, 15)
replaced_arr = np.where(rand_arr > 50, -1, rand_arr)
count_replaced = np.sum(rand_arr > 50)
print("\nOriginal:\n", rand_arr)
print("Replaced (>50 with -1):\n", replaced_arr)
print("Count of replaced values:", count_replaced)


Original:
 [ 26 100  89  89  87  29  44  21  69  43  51  20  87  85  89]
Replaced (>50 with -1):
 [26 -1 -1 -1 -1 29 44 21 -1 43 -1 20 -1 -1 -1]
Count of replaced values: 9


5×4 random array, row with max sum, normalize each row

In [ ]:
rand_5x4 = np.random.rand(5, 4)
row_max_sum_index = np.argmax(rand_5x4.sum(axis=1))
normalized = rand_5x4 / rand_5x4.sum(axis=1, keepdims=True)
print("\nRow with maximum sum index:", row_max_sum_index)
print("Normalized rows:\n", normalized)


Row with maximum sum index: 3
Normalized rows:
 [[0.37560102 0.25709394 0.34313891 0.02416613]
 [0.41485587 0.38841201 0.02746139 0.16927074]
 [0.12324304 0.33588088 0.34542279 0.19545329]
 [0.14161586 0.29330071 0.15597618 0.40910725]
 [0.33280635 0.1032932  0.24507138 0.31882907]]


Unique & duplicates in arr

In [ ]:
arr5 = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_elements = np.unique(arr5)
duplicates = [x for x in unique_elements if np.sum(arr5 == x) > 1]
print("\nUnique Elements:", unique_elements)
print("Duplicates:", duplicates)


Unique Elements: [1 3 5 7 9]
Duplicates: [np.int64(1), np.int64(3), np.int64(5)]


6×6 array, extract middle 4×4, even numbers

In [ ]:
arr6 = np.arange(1, 37).reshape(6, 6)
middle_4x4 = arr6[1:5, 1:5]
even_numbers = middle_4x4[middle_4x4 % 2 == 0]
print("\nMiddle 4×4 Submatrix:\n", middle_4x4)
print("Even Numbers in Submatrix:", even_numbers)


Middle 4×4 Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
Even Numbers in Submatrix: [ 8 10 14 16 20 22 26 28]


(3,4) -> (2,6) -> flatten -> (4,3)

In [ ]:
arr7 = np.arange(12).reshape(3, 4)
reshaped_2x6 = arr7.reshape(2, 6)
flattened = reshaped_2x6.flatten()
reshaped_4x3 = flattened.reshape(4, 3)
print("\nReshaped to (4,3):\n", reshaped_4x3)


Reshaped to (4,3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Append new row & column

In [ ]:
a = np.array([[1, 2], [3, 4]])
a = np.vstack([a, [5, 6]])          # Add row
a = np.column_stack([a, [7, 8, 9]]) # Add column
print("\nAfter Appending Row & Column:\n", a)


After Appending Row & Column:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


Join arrays, reshape to 3x3, extract diagonal

In [ ]:
a9 = np.array([1, 2, 3])
b9 = np.array([4, 5, 6])
c9 = np.array([7, 8, 9])
joined = np.concatenate([a9, b9, c9]).reshape(3, 3)
diagonal = np.diag(joined)
print("\nDiagonal Elements:", diagonal)


Diagonal Elements: [1 5 9]


Integers from 1 to 20, divisible by 3 or 5

In [ ]:
arr10 = np.arange(1, 21)
divisible = arr10[(arr10 % 3 == 0) | (arr10 % 5 == 0)]
count_divisible = len(divisible)
print("\nDivisible by 3 or 5:", divisible)
print("Count:", count_divisible)


Divisible by 3 or 5: [ 3  5  6  9 10 12 15 18 20]
Count: 9


# Pandas

In [ ]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
print("1. First 10 Rows:\n", df.head(10))

1. First 10 Rows:
    PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Ti

In [ ]:
print("\n2. Missing Values:\n", df.isnull().sum())


2. Missing Values:
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [ ]:
survival_percentage = df.groupby('Sex')['Survived'].mean() * 100
print("\n3. Survival Percentage by Gender (%):\n", survival_percentage)


3. Survival Percentage by Gender (%):
 Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64


In [ ]:
avg_age = df['Age'].mean()
median_age = df['Age'].median()
std_age = df['Age'].std()
print(f"\n4. Age Stats -> Avg: {avg_age:.2f}, Median: {median_age:.2f}, Std Dev: {std_age:.2f}")


4. Age Stats -> Avg: 29.70, Median: 28.00, Std Dev: 14.53


In [ ]:
pclass_count = df['Pclass'].value_counts()
print("\n5. Passenger Count by Class:\n", pclass_count)


5. Passenger Count by Class:
 Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [ ]:
female_under18_survived = df[(df['Sex'] == 'female') & (df['Age'] < 18) & (df['Survived'] == 1)]
print("\n6. Female Passengers <18 & Survived:\n", female_under18_survived)


6. Female Passengers <18 & Survived:
      PassengerId  Survived  Pclass  \
9             10         1       2   
10            11         1       3   
22            23         1       3   
39            40         1       3   
43            44         1       2   
58            59         1       2   
68            69         1       3   
84            85         1       2   
156          157         1       3   
172          173         1       3   
184          185         1       3   
208          209         1       3   
233          234         1       3   
237          238         1       2   
307          308         1       1   
329          330         1       1   
381          382         1       3   
389          390         1       2   
435          436         1       1   
446          447         1       2   
448          449         1       3   
469          470         1       3   
479          480         1       3   
504          505         1       1   
530        

In [ ]:
df['Age'].fillna(median_age, inplace=True)
print("\n7. Missing Ages Filled with Median.")


7. Missing Ages Filled with Median.


/tmp/ipython-input-3775223418.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(median_age, inplace=True)


In [ ]:
df['age_group'] = np.where(df['Age'] < 18, 'Child',
                    np.where(df['Age'] <= 60, 'Adult', 'Senior'))
print("\n8. Added age_group column:\n", df[['Age', 'age_group']].head(10))


8. Added age_group column:
     Age age_group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult
5  28.0     Adult
6  54.0     Adult
7   2.0     Child
8  27.0     Adult
9  14.0     Child


In [ ]:
top5_fare = df.sort_values(by='Fare', ascending=False).head(5)
print("\n9. Top 5 Highest Fare Passengers:\n", top5_fare[['Name', 'Fare']])


9. Top 5 Highest Fare Passengers:
                                    Name      Fare
679  Cardeza, Mr. Thomas Drake Martinez  512.3292
258                    Ward, Miss. Anna  512.3292
737              Lesurer, Mr. Gustave J  512.3292
88           Fortune, Miss. Mabel Helen  263.0000
438                   Fortune, Mr. Mark  263.0000


In [ ]:
avg_fare_grouped = df.groupby(['Pclass', 'Sex'])['Fare'].mean()
print("\n10. Average Fare by Class & Gender:\n", avg_fare_grouped)


10. Average Fare by Class & Gender:
 Pclass  Sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64


In [ ]:
df.rename(columns={'Sex': 'gender', 'Fare': 'ticket_fare'}, inplace=True)
print("\n11. Columns Renamed.")


11. Columns Renamed.


In [ ]:
survival_by_class = df.groupby(['Pclass', 'Survived']).size()
print("\n12. Survival Count by Class:\n", survival_by_class)


12. Survival Count by Class:
 Pclass  Survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
dtype: int64


In [ ]:
avg_age_grouped = df.groupby(['Pclass', 'gender'])['Age'].mean()
print("\n13. Average Age by Class & Gender:\n", avg_age_grouped)


13. Average Age by Class & Gender:
 Pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: Age, dtype: float64
