<a href="https://colab.research.google.com/github/FIROZ-N/DSA-2025/blob/main/Numpy_Assignment_Firoz_Muhammed_N.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 NumPy array with values from 10 to 49 (inclusive).

 ----

● Reshape it into a 4x10 matrix.

----

● Then extract the last column from the reshaped matrix

In [21]:
import numpy as np

arr = np.arange(10,50)

matrix = arr.reshape(4,10)

print()

print(f"matrix : {matrix}")

last_column = matrix[:,-1]

print(f"last : {last_column}")



matrix : [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
last : [19 29 39 49]


Two 3×3 matrices:

---
One filled with all 5s , One with values from 1 to 9

---
● Add the two matrices

---
● Multiply them element-wise

---
● Then find the transpose of the result

In [22]:
import numpy as np

mat1 = np.full((3, 3), 5)
mat2 = np.arange(1, 10).reshape(3, 3)
added = mat1 + mat2
multiplied = mat1 * mat2
transpose_result = multiplied.T
print("\nTranspose of Element-wise Multiplication:\n", transpose_result)


Transpose of Element-wise Multiplication:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


A NumPy array of 15 random integers between 10 and 100.

----
● Replace all values greater than 50 with -1

----
● Count how many values were replaced.

In [23]:
rand_arr = np.random.randint(10, 101, 15)
replaced_arr = np.where(rand_arr > 50, -1, rand_arr)
count_replaced = np.sum(rand_arr > 50)
print("\nOriginal:\n", rand_arr)
print("Replaced (>50 with -1):\n", replaced_arr)
print("Count of replaced values:", count_replaced)


Original:
 [37 67 70 36 19 97 40 37 27 28 21 24 84 57 90]
Replaced (>50 with -1):
 [37 -1 -1 36 19 -1 40 37 27 28 21 24 -1 -1 -1]
Count of replaced values: 6


5×4 random array, row with max sum, normalize each row

In [24]:
rand_5x4 = np.random.rand(5, 4)
row_max_sum_index = np.argmax(rand_5x4.sum(axis=1))
normalized = rand_5x4 / rand_5x4.sum(axis=1, keepdims=True)
print("\nRow with maximum sum index:", row_max_sum_index)
print("Normalized rows:\n", normalized)


Row with maximum sum index: 2
Normalized rows:
 [[0.34679814 0.2920137  0.31058426 0.0506039 ]
 [0.28584322 0.19766311 0.22774147 0.2887522 ]
 [0.33845519 0.2703091  0.34467788 0.04655783]
 [0.35150538 0.23527979 0.27432127 0.13889355]
 [0.3311772  0.00772922 0.2619839  0.39910968]]


Unique & duplicates in arr

In [25]:
arr5 = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_elements = np.unique(arr5)
duplicates = [x for x in unique_elements if np.sum(arr5 == x) > 1]
print("\nUnique Elements:", unique_elements)
print("Duplicates:", duplicates)


Unique Elements: [1 3 5 7 9]
Duplicates: [np.int64(1), np.int64(3), np.int64(5)]


6×6 array, extract middle 4×4, even numbers

In [26]:
arr6 = np.arange(1, 37).reshape(6, 6)
middle_4x4 = arr6[1:5, 1:5]
even_numbers = middle_4x4[middle_4x4 % 2 == 0]
print("\nMiddle 4×4 Submatrix:\n", middle_4x4)
print("Even Numbers in Submatrix:", even_numbers)


Middle 4×4 Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
Even Numbers in Submatrix: [ 8 10 14 16 20 22 26 28]


(3,4) -> (2,6) -> flatten -> (4,3)

In [27]:
arr7 = np.arange(12).reshape(3, 4)
reshaped_2x6 = arr7.reshape(2, 6)
flattened = reshaped_2x6.flatten()
reshaped_4x3 = flattened.reshape(4, 3)
print("\nReshaped to (4,3):\n", reshaped_4x3)


Reshaped to (4,3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Append new row & column

In [28]:
a = np.array([[1, 2], [3, 4]])
a = np.vstack([a, [5, 6]])          # Add row
a = np.column_stack([a, [7, 8, 9]]) # Add column
print("\nAfter Appending Row & Column:\n", a)


After Appending Row & Column:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


Join arrays, reshape to 3x3, extract diagonal

In [29]:
a9 = np.array([1, 2, 3])
b9 = np.array([4, 5, 6])
c9 = np.array([7, 8, 9])
joined = np.concatenate([a9, b9, c9]).reshape(3, 3)
diagonal = np.diag(joined)
print("\nDiagonal Elements:", diagonal)


Diagonal Elements: [1 5 9]


Integers from 1 to 20, divisible by 3 or 5

In [30]:
arr10 = np.arange(1, 21)
divisible = arr10[(arr10 % 3 == 0) | (arr10 % 5 == 0)]
count_divisible = len(divisible)
print("\nDivisible by 3 or 5:", divisible)
print("Count:", count_divisible)


Divisible by 3 or 5: [ 3  5  6  9 10 12 15 18 20]
Count: 9
